spring.datasource.url=jdbc:postgresql://localhost:5432/plantcare
spring.datasource.username=plantcare
spring.datasource.password=plantcare
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

logging.level.com.example.plantcare=DEBUG
debug=true


#spring.thymeleaf.cache=false
